# Generated by Django 4.1.1 on 2022-10-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_name', models.CharField(max_length=255)),
                ('router_ip', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DevicesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_name', models.CharField(max_length=255)),
                ('router_ip', models.CharField(max_length=255)),
                ('router_type', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=255)),
                ('memory_usage', models.CharField(max_length=255)),
                ('cpu_usage', models.CharField(max_length=255)),
                ('uptime', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=255)),
                ('user_pppoe', models.CharField(max_length=255)),
                ('uptime', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('ip_address', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255)),
                ('rx_upload', models.CharField(max_length=255)),
                ('tx_download', models.CharField(max_length=255)),
                ('identity_router', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
