# Generated by Django 4.1.1 on 2022-10-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='rx_upload',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tx_download',
            field=models.IntegerField(),
        ),
    ]
