# Generated by Django 4.1.1 on 2022-10-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0002_alter_userinfo_rx_upload_alter_userinfo_tx_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='rx_upload',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tx_download',
            field=models.BigIntegerField(),
        ),
    ]
