# Generated by Django 4.1.1 on 2022-10-07 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0004_devicesinfo_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_name', models.CharField(max_length=255)),
                ('interface_name', models.CharField(max_length=255)),
                ('type_interface', models.CharField(max_length=255)),
                ('router_ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitor_app.devicesinfo')),
            ],
        ),
    ]
