# Generated by Django 4.1.1 on 2022-10-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0006_listinterface_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listinterface',
            name='router_ip',
            field=models.CharField(max_length=255),
        ),
    ]
