# Generated by Django 4.1.1 on 2022-10-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0007_alter_listinterface_router_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficAgg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_ip', models.CharField(max_length=255)),
                ('router_name', models.CharField(max_length=255)),
                ('download', models.BigIntegerField()),
                ('upload', models.BigIntegerField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
