# Generated by Django 4.1.1 on 2022-10-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0008_trafficagg'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficagg',
            name='cpu_load',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
