# Generated by Django 4.1.1 on 2022-10-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0009_trafficagg_cpu_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='router_ip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
