# Generated by Django 4.1.1 on 2022-10-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0010_userinfo_router_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficagg',
            name='cpu_load',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
