# Generated by Django 4.1.1 on 2022-10-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0011_alter_trafficagg_cpu_load'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficagg',
            name='cpu_load',
        ),
    ]
