# Generated by Django 4.1.1 on 2022-10-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0012_remove_trafficagg_cpu_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficagg',
            name='cpu_load',
            field=models.IntegerField(null=True),
        ),
    ]
