# Generated by Django 4.1.1 on 2022-10-20 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0013_trafficagg_cpu_load'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficagg',
            name='cpu_load',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trafficagg',
            name='download',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trafficagg',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trafficagg',
            name='upload',
            field=models.CharField(max_length=255),
        ),
    ]
