# Generated by Django 4.1.1 on 2022-10-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0014_alter_trafficagg_cpu_load_alter_trafficagg_download_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrafficAccumulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('router_ip', models.CharField(max_length=255)),
                ('router_name', models.CharField(max_length=255)),
                ('user_pppoe', models.CharField(max_length=255)),
                ('old_rx_upload', models.BigIntegerField()),
                ('old_tx_download', models.BigIntegerField()),
                ('rx_upload', models.BigIntegerField()),
                ('tx_download', models.BigIntegerField()),
            ],
        ),
    ]
