# Generated by Django 4.1.1 on 2024-10-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0017_device_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='vendor',
            field=models.CharField(choices=[('cisco', 'Cisco'), ('mikrotik', 'Mikrotik')], max_length=255),
        ),
    ]
