# Generated by Django 4.1.1 on 2024-10-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0018_alter_device_vendor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
